## This function takes inversable matrics and return a vector of methods that can be performed on this matrix
## Methods:
## - get() - returns initialised matrix value
## - set(M) - reset matrix to a new value M
## - getinvert() - returns cached value of inverse of initialised matrix. Returns NULL if inverse was not cached yet
## - setinvert(inverse) - cache inverse of initialised matrix
##
## Example
## x<- makeCacheMatrix(matrix(1:4, 2, 2))

makeCacheMatrix <- function(x = matrix()) {
  inv <- NULL
  
  set <- function(y) {
    x <<- y
    inv <<- NULL
  }
  
  get <- function() x
  
  setinvert <- function(inverse) inv <<- inverse
  
  getinvert <- function() inv
  
  list(set = set, get = get, setinvert = setinvert, getinvert = getinvert)
}

## This function takes object (ie special vector) generated by makeCacheMatrix and returns inverse of the initialised matrix.
## If the method was called before for the same matrix then this function will return cached inverse
## alternatevily it will calculate inverse of a new matrix and cache it using "setinvert" method of makeCacheMatrix object
## Example
## m <- makeCacheMatrix(matrix(1:4, 2, 2))
## x <- cacheSolve(m)
## x
## y <- cacheSolve(m)
## y


cacheSolve <- function(x, ...) {
  inv <- x$getinvert()
  if(!is.null(inv)) {
    message("Getting cached inverse")
    return(inv)
  }
  message("Calculating new inverse")
  data <- x$get()
  inv <- solve(data, ...)
  x$setinvert(inv)
  inv
}

